from PyQt5.QtWidgets import *

app = QApplication([])
window = QWidget()
layout = QVBoxLayout()
tabs = QTabWidget()
mainTab = QWidget()
mainTabLayout = QVBoxLayout()
tableTab = QWidget()
ttLayout = QVBoxLayout()
oneEdit = QLineEdit()
twoEdit = QLineEdit()
addButton = QPushButton("Add")
subButton = QPushButton("Subtract")
multiplyButton = QPushButton("Multiply")
divButton = QPushButton("Divide")
expButton = QPushButton("Exponent")
outputLabel = QLabel()
table = QTableWidget()

table.setColumnCount(4)
table.setRowCount(0)
table.setHorizontalHeaderLabels(["x", "y", "output", "action"])

mainTabLayout.addWidget(oneEdit)
mainTabLayout.addWidget(twoEdit)
mainTabLayout.addWidget(addButton)
mainTabLayout.addWidget(subButton)
mainTabLayout.addWidget(multiplyButton)
mainTabLayout.addWidget(divButton)
mainTabLayout.addWidget(expButton)
mainTabLayout.addWidget(outputLabel)
mainTab.setLayout(mainTabLayout)
tabs.addTab(mainTab, "Calculator")

ttLayout.addWidget(table)
tableTab.setLayout(ttLayout)
tabs.addTab(tableTab, "History")

def add():
    x = oneEdit.text()
    y = twoEdit.text()
    z = str(int(x) + int(y))
    outputLabel.setText(z)
    rowCount = table.rowCount()
    table.insertRow(rowCount)
    table.setItem(rowCount, 0, QTableWidgetItem(x))
    table.setItem(rowCount, 1, QTableWidgetItem(y))
    table.setItem(rowCount, 2, QTableWidgetItem(z))
    table.setItem(rowCount, 3, QTableWidgetItem("Addition"))

def sub():
    x = oneEdit.text()
    y = twoEdit.text()
    z = str(int(x) - int(y))
    outputLabel.setText(z)
    rowCount = table.rowCount()
    table.insertRow(rowCount)
    table.setItem(rowCount, 0, QTableWidgetItem(x))
    table.setItem(rowCount, 1, QTableWidgetItem(y))
    table.setItem(rowCount, 2, QTableWidgetItem(z))
    table.setItem(rowCount, 3, QTableWidgetItem("Subtracktor"))

def multiply():
    x = oneEdit.text()
    y = twoEdit.text()
    z = str(int(x) * int(y))
    outputLabel.setText(z)
    rowCount = table.rowCount()
    table.insertRow(rowCount)
    table.setItem(rowCount, 0, QTableWidgetItem(x))
    table.setItem(rowCount, 1, QTableWidgetItem(y))
    table.setItem(rowCount, 2, QTableWidgetItem(z))
    table.setItem(rowCount, 3, QTableWidgetItem("Multiplication"))

def div():
    x = oneEdit.text()
    y = twoEdit.text()
    z = str(int(x) / int(y))
    outputLabel.setText(z)
    rowCount = table.rowCount()
    table.insertRow(rowCount)
    table.setItem(rowCount, 0, QTableWidgetItem(x))
    table.setItem(rowCount, 1, QTableWidgetItem(y))
    table.setItem(rowCount, 2, QTableWidgetItem(z))
    table.setItem(rowCount, 3, QTableWidgetItem("Division"))

def exp():
    x = oneEdit.text()
    y = twoEdit.text()
    z = str(int(x) ** int(y))
    outputLabel.setText(z)
    rowCount = table.rowCount()
    table.insertRow(rowCount)
    table.setItem(rowCount, 0, QTableWidgetItem(x))
    table.setItem(rowCount, 1, QTableWidgetItem(y))
    table.setItem(rowCount, 2, QTableWidgetItem(z))
    table.setItem(rowCount, 3, QTableWidgetItem("Exponent"))

addButton.clicked.connect(add)
subButton.clicked.connect(sub)
multiplyButton.clicked.connect(multiply)
divButton.clicked.connect(div)
expButton.clicked.connect(exp)

layout.addWidget(tabs)
window.setLayout(layout)
window.show()
app.exec_()